-- MySQL Script generated by MySQL Workbench
-- Sun 04 Apr 2021 09:01:12 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema students_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema students_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `students_database` DEFAULT CHARACTER SET ascii ;
USE `students_database` ;

-- -----------------------------------------------------
-- Table `students_database`.`majors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students_database`.`majors` (
  `major_id` INT NOT NULL AUTO_INCREMENT,
  `major_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`major_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `students_database`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students_database`.`students` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `student_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `major` INT NOT NULL,
  PRIMARY KEY (`student_id`),
  INDEX `fk_major_id_idx` (`major` ASC) VISIBLE,
  CONSTRAINT `fk_major_id`
    FOREIGN KEY (`major`)
    REFERENCES `students_database`.`majors` (`major_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `students_database`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students_database`.`classes` (
  `class_id` INT NOT NULL AUTO_INCREMENT,
  `class_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`class_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `students_database`.`student_schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students_database`.`student_schedules` (
  `student_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `class_id`),
  INDEX `fk_class_id_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_schedules_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `students_database`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_id`
    FOREIGN KEY (`class_id`)
    REFERENCES `students_database`.`classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

